import matplotlib.pyplot as plt

# Pontos A e B
A = (-5, 1)
B = (1, 3)

# Subquestão (a): B = A + 2v → v = (3, 1)
v_a = (3, 1)

# Subquestão (b): A = B + 3v → v = (-2, -2/3)
v_b = (-2, -2/3)

# fig, axes = plt.subplots(1, 2, figsize=(12, 5))
#
# # Plot (a)
# axes[0].quiver(*A, *v_a, angles='xy', scale_units='xy', scale=1, color='blue', label='v')
# axes[0].scatter(*A, color='black')
# axes[0].scatter(*B, color='red')
# axes[0].text(*A, 'A', fontsize=12, ha='right')
# axes[0].text(*B, 'B', fontsize=12, ha='left')
# axes[0].set_title("(a) $\\vec{v} = (3, 1)$")
# axes[0].set_xlim(-6, 3)
# axes[0].set_ylim(0, 5)
# axes[0].grid(True)
# axes[0].set_aspect('equal')
#
# # Plot (b)
# axes[1].quiver(*B, *v_b, angles='xy', scale_units='xy', scale=1, color='green', label='v')
# axes[1].scatter(*A, color='black')
# axes[1].scatter(*B, color='red')
# axes[1].text(*A, 'A', fontsize=12, ha='right')
# axes[1].text(*B, 'B', fontsize=12, ha='left')
# axes[1].set_title("(b) $\\vec{v} = (-2, -\\frac{2}{3})$")
# axes[1].set_xlim(-7, 3)
# axes[1].set_ylim(-1, 5)
# axes[1].grid(True)
# axes[1].set_aspect('equal')

fig, ax = plt.subplots()

# # Plot (a)
# ax.quiver(*A, *v_a, angles='xy', scale_units='xy', scale=1, color='blue', label='v')
# ax.scatter(*A, color='black')
# ax.scatter(*B, color='red')
# ax.text(*A, 'A', fontsize=12, ha='right')
# ax.text(*B, 'B', fontsize=12, ha='left')
# ax.set_title("(a) $\\vec{v} = (3, 1)$")
# ax.set_xlim(-6, 3)
# ax.set_ylim(0, 5)
# ax.grid(True)
# ax.set_aspect('equal')

# Plot (b)
ax.quiver(*B, *v_b, angles='xy', scale_units='xy', scale=1, color='green', label='v')
ax.scatter(*A, color='black')
ax.scatter(*B, color='red')
ax.text(*A, 'A', fontsize=12, ha='right')
ax.text(*B, 'B', fontsize=12, ha='left')
ax.set_title("(b) $\\vec{v} = (-2, -\\frac{2}{3})$")
ax.set_xlim(-7, 3)
ax.set_ylim(-1, 5)
ax.grid(True)
ax.set_aspect('equal')

plt.show()
